#!/bin/sh

ARCHIVE=$(awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' "$0")

TMPDIR=$(mktemp -d)

trap 'rm -rf "$TMPDIR"' EXIT

tail -n +$ARCHIVE "$0" | tar -I zstd -xf - -C "$TMPDIR" || { echo "Extraction failed!"; exit 1; }

cd "$TMPDIR" || exit 1


chmod +x vmgr.sh

DIR=$TMPDIR ./vmgr.sh "$@"

rm -rf "$TMPDIR"

exit 0

__ARCHIVE_BELOW__
